site_name: PBR Painter
nav:
   - index.md
   - getting_started.md
   - addon_UI.md
   - layering_intro.md
   - layer_masks.md
   - asset_browser.md
   - id_maps.md
   - baking.md
   - hands_on_tutorials.md
   - change_log.md
   - version_3_alpha.md
   - final_note.md
theme: readthedocs
use_directory_urls: false